### ISSUE TITLE
Error when deploying to Netlify

### ISSUE THREAD

**Issue by tenzan** [carrot/ship#76]
Sometimes I have the following error when deploying to netlify.
Error message does not give me a clue what's wrong with the code...

```
{ [Error: socket hang up] code: 'ECONNRESET' }
Potentially unhandled rejection [4] Error: socket hang up
  at createHangUpError (_http_client.js:210:15)
  at TLSSocket.socketOnEnd (_http_client.js:295:23)
  at emitNone (events.js:73:20)
  at TLSSocket.emit (events.js:167:7)
  at endReadableNT (_stream_readable.js:906:12)
  at nextTickCallbackWith2Args (node.js:455:9)
  at process._tickCallback (node.js:369:17)
```

**Comment by tenzan** [comment]
Error has gone when I pushed a commit.
